version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80 
    volumes:
      - ..:/workspace
    user: vscode
    command: sleep infinity
    entrypoint: /etc/supervisor/build.sh
    container_name: app
  
  mysql:
    image: "mysql:8.0.33"
    restart: unless-stopped
    environment:
      MYSQL_USER: homestead
      MYSQL_PASSWORD: H0m3st3ad
      MYSQL_ROOT_PASSWORD: H0m3st3ad
      MYSQL_DATABASE: homestead
    ports:
        - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql  
    container_name: mysql

  sqlsrv:
    image: mcr.microsoft.com/mssql/server
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: H0m3st3ad
    ports:
      - 1433:1433
    volumes:
      - sqlsrvdata:/var/opt/mssql/data
      - sqlsrvdata:/var/opt/mssql/log
      - sqlsrvdata:/var/opt/mssql/secrets
    user: root
    container_name: sqlsrv

  postgres:
    image: "postgres:15.3"
    restart: unless-stopped
    environment:
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: H0m3st3ad
      POSTGRES_DB: homestead
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data
    container_name: postgres
  
  mongodb:
    image: "mongo:6.0.4"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: homestead
      MONGO_INITDB_ROOT_PASSWORD: H0m3st3ad
    ports:
        - 27017:27017
    volumes:
      - mongodata:/data/db
    container_name: mongodb

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/ -port 8081
    volumes:
     - dynamodbdata:/home/dynamodblocal/data
    ports:
     - "8081:8081"
    user: root
    container_name: dynamodb
  
  redis:
    image: "redis:6.2.11"
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=H0m3st3ad
    command: '--requirepass H0m3st3ad'
    ports:
        - 6379:6379
    volumes:
      - redisdata:/data
    container_name: redis

volumes:
  mysqldata:
  pgdata:
  sqlsrvdata:
  mongodata:
  dynamodbdata:
  redisdata: